name: Deploy to Github Pages

on:
  push:
    paths:
    - 'index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/setup-pages@v2

    - name: Deploy
      run: |
        echo "Deploying website"
        mkdir -p ./public
        cp index.html ./public/index.html
        echo "<meta http-equiv='refresh' content='0; url=./public/index.html'>" > ./public/404.html
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./public
        git commit -m "Deploy website"
        git push origin gh-pages
